TE7-T122 Active Record Associations
Dhyey54/rails-practice pull request #8
Opened 2023-04-03 11:50 UTC by Dhyey54

Assignment submission for active record association

2023-04-13 10:24 UTC, poonamsimform commented on app/controllers/addresses_controller.rb
> +    @address = Address.find_by(user_id: @current_user[:id])
Please use @current_user.id

2023-04-13 10:24 UTC, poonamsimform commented on app/controllers/application_controller.rb
> +      @enrolled_event = Enrollment.where(user_id: @current_user[:id], created: false).pluck(:event_id)
same here.

2023-04-13 10:24 UTC, poonamsimform commented on app/controllers/profile_controller.rb
> +    if @profile.update(profile_params)
When are we creating the Profile?

2023-04-13 10:24 UTC, poonamsimform commented on app/controllers/addresses_controller.rb
> +  def user_address
Leave one line before `user_address` action

2023-04-13 10:24 UTC, poonamsimform commented on db/migrate/20230330050515_create_enrollments.rb
> +      t.boolean :created
Instead of using the "created" column, it would be helpful if you could use a more descriptive field name like "enrolled" to make it clearer what this column represents.

2023-04-13 10:24 UTC, poonamsimform commented on app/controllers/comments_controller.rb
> +    @comments = Comment.where(user_id: @current_user[:id])
Same here use `@current_user.id`

2023-04-13 10:24 UTC, poonamsimform commented on app/views/comments/event_comments.html.erb
> +      <% if comment.user_id == @current_user.id%>
Space before %

2023-04-13 10:24 UTC, poonamsimform commented on app/controllers/addresses_controller.rb
> +  def update
From when are we creating the address?

2023-04-13 11:13 UTC, Dhyey54 commented on app/controllers/addresses_controller.rb
> +  def update
It is created from console for users.

2023-04-13 11:14 UTC, Dhyey54 commented on app/controllers/profile_controller.rb
> +    if @profile.update(profile_params)
Profile is created for user from console.

2023-05-03 10:37 UTC, poonamsimform requested changes

2023-05-03 10:37 UTC, poonamsimform commented on app/controllers/comments_controller.rb
> +    @comment = Comment.new(user_comment: comment_params[:user_comment], event_id: params[:event_id], user_id: @current_user.id)
Please use `comment_params`

2023-05-03 10:37 UTC, poonamsimform commented on app/controllers/events_controller.rb
> +    @events = Event.where(id: Enrollment.where(user_id: @current_user.id, owner: true).pluck(:event_id)).order(id: :desc)
Please optimize this query

2023-05-03 10:37 UTC, poonamsimform commented on app/controllers/events_controller.rb
> +    @comments = Event.find(params[:id]).comments
Can we please use `@event.comments` to find the comments instead of writing `find` query

2023-05-03 10:37 UTC, poonamsimform commented on app/controllers/events_controller.rb
> +    @event = Event.find_by(id: Enrollment.where(user_id: @current_user.id, event_id: params[:id], owner: true).pluck(:event_id))
same here. optimize query

2023-05-03 10:37 UTC, poonamsimform commented on app/views/profile/index.html.erb
> +  </tr>
What if a profile is not created?

2023-05-03 10:37 UTC, poonamsimform commented on app/views/profile/index.html.erb
> +  </tr>
Same, what is the address is not created from the console?

2023-05-03 10:37 UTC, poonamsimform commented on app/controllers/comments_controller.rb
> +    @event = Event.find(params[:eventid])
Please create one action for finding event_id and apply filter action for `new and event_comments` and optimize event_comments mathod

2023-05-03 10:37 UTC, poonamsimform commented on app/views/comments/event_comments.html.erb
> +      <% if comment.user.id != @current_user.id %>
Is `comment.user.id and comment.user_id` both are different?
Also, if you want to use `comment.user.id` to check the condition then please use the `comment.user != @current_user`

2023-05-03 10:37 UTC, poonamsimform commented on app/views/comments/event_comments.html.erb
> +        <% if comment.likes.pluck("user_id").include?(comment.user_id) || comment.likes.pluck("user_id").include?(@current_user.id) %>
Please move this in helper method

2023-05-03 10:37 UTC, poonamsimform commented on app/views/comments/user_comments.html.erb
> +      <td><%= comment.usercomment %></td>
Is it correct variable name?

2023-05-03 10:37 UTC, poonamsimform commented on app/views/enrollments/index.html.erb
> +      <% if @enrolled_event.include?(event.id) %>
Why we have added this condition here?

2023-06-20 07:29 UTC, poonamsimform approved these changes
Please resolve the conflicts and after that merge this PR

2023-06-20 08:06 UTC, merged